"""Template context processors for the control app."""


def csp_nonce(request):
    """Expose the per-request CSP nonce generated by SecurityHeadersMiddleware."""
    return {'csp_nonce': getattr(request, 'csp_nonce', '')}
