# Generated by Django 5.2.12 on 2026-03-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                (
                    "label",
                    models.CharField(
                        help_text='Button-Beschriftung, z.B. "Migrate"', max_length=80
                    ),
                ),
                (
                    "command",
                    models.CharField(
                        help_text='manage.py Unterbefehl, z.B. "migrate" oder "load_glossary"',
                        max_length=500,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Sortierung (aufsteigend)"
                    ),
                ),
            ],
            options={
                "ordering": ["project_name", "order", "label"],
                "unique_together": {("project_name", "command")},
            },
        ),
    ]
