# Generated by Django 4.2.30 on 2026-06-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control", "0003_encrypt_totp_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("mem_percent", models.IntegerField(blank=True, null=True)),
                ("disk_percent", models.IntegerField(blank=True, null=True)),
                ("load1", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False, help_text="Benachrichtigungen aktivieren."
                    ),
                ),
                ("email_enabled", models.BooleanField(default=False)),
                (
                    "email_to",
                    models.CharField(
                        blank=True,
                        help_text="Empfänger, kommasepariert.",
                        max_length=255,
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.IntegerField(default=587)),
                ("smtp_user", models.CharField(blank=True, max_length=255)),
                ("smtp_password", models.CharField(blank=True, max_length=255)),
                ("smtp_from", models.CharField(blank=True, max_length=255)),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("webhook_enabled", models.BooleanField(default=False)),
                ("webhook_url", models.URLField(blank=True, max_length=500)),
                ("notify_backup_failure", models.BooleanField(default=True)),
                ("notify_service_down", models.BooleanField(default=True)),
                ("notify_vulnerabilities", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
            },
        ),
    ]
